server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: woaa-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: woaa-logs
          __path__: /var/log/*.log # Path to your JSON logs

    pipeline_stages:
      # 1️⃣ Parse the JSON log line
      - json:
          expressions:
            timestamp: timestamp
            log_id: log_id
            session_id: session_id
            device: device
            username: username
            level: level
            event_type: event_type
            status: status
            error_msg: error_msg
            location: location
            additional_info: additional_info
            notes: notes

      # 3️⃣ Add all fields as labels in Loki
      - labels:
          timestamp:
          log_id:
          session_id:
          device:
          username:
          level:
          event_type:
          status:
          error_msg:
          location:
          additional_info:
          notes:
