"""add last_updated to user_settings

Revision ID: 309c69dc9c18
Revises: b7e8248a4bb8
Create Date: 2025-06-26 04:20:25.611774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309c69dc9c18'
down_revision: Union[str, Sequence[str], None] = 'b7e8248a4bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
